// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Internal.proto

package io.drake.im.protobuf.generate;

public final class IMInternal {
  private IMInternal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InternalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.Internal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .message.Internal.Module origin = 1;</code>
     * @return Whether the origin field is set.
     */
    boolean hasOrigin();
    /**
     * <code>optional .message.Internal.Module origin = 1;</code>
     * @return The origin.
     */
    Internal.Module getOrigin();

    /**
     * <code>optional .message.Internal.Module dest = 2;</code>
     * @return Whether the dest field is set.
     */
    boolean hasDest();
    /**
     * <code>optional .message.Internal.Module dest = 2;</code>
     * @return The dest.
     */
    Internal.Module getDest();

    /**
     * <code>optional .message.Internal.MsgType msgType = 3;</code>
     * @return Whether the msgType field is set.
     */
    boolean hasMsgType();
    /**
     * <code>optional .message.Internal.MsgType msgType = 3;</code>
     * @return The msgType.
     */
    Internal.MsgType getMsgType();

    /**
     * <code>optional string body = 4;</code>
     * @return Whether the body field is set.
     */
    boolean hasBody();
    /**
     * <code>optional string body = 4;</code>
     * @return The body.
     */
    String getBody();
    /**
     * <code>optional string body = 4;</code>
     * @return The bytes for body.
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>optional int64 internalId = 5;</code>
     * @return Whether the internalId field is set.
     */
    boolean hasInternalId();
    /**
     * <code>optional int64 internalId = 5;</code>
     * @return The internalId.
     */
    long getInternalId();

    /**
     * <code>optional int64 createTime = 6;</code>
     * @return Whether the createTime field is set.
     */
    boolean hasCreateTime();
    /**
     * <code>optional int64 createTime = 6;</code>
     * @return The createTime.
     */
    long getCreateTime();
  }
  /**
   * Protobuf type {@code message.Internal}
   */
  public static final class Internal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.Internal)
      InternalOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Internal.newBuilder() to construct.
    private Internal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Internal() {
      origin_ = 1;
      dest_ = 1;
      msgType_ = 1;
      body_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Internal();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Internal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              Module value = Module.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                origin_ = rawValue;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              Module value = Module.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                dest_ = rawValue;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              MsgType value = MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                msgType_ = rawValue;
              }
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              body_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              internalId_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              createTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMInternal.internal_static_message_Internal_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMInternal.internal_static_message_Internal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Internal.class, Builder.class);
    }

    /**
     * Protobuf enum {@code message.Internal.Module}
     */
    public enum Module
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CLIENT = 1;</code>
       */
      CLIENT(1),
      /**
       * <code>CONNECTOR = 2;</code>
       */
      CONNECTOR(2),
      /**
       * <code>TRANSFER = 3;</code>
       */
      TRANSFER(3),
      ;

      /**
       * <code>CLIENT = 1;</code>
       */
      public static final int CLIENT_VALUE = 1;
      /**
       * <code>CONNECTOR = 2;</code>
       */
      public static final int CONNECTOR_VALUE = 2;
      /**
       * <code>TRANSFER = 3;</code>
       */
      public static final int TRANSFER_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Module valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Module forNumber(int value) {
        switch (value) {
          case 1: return CLIENT;
          case 2: return CONNECTOR;
          case 3: return TRANSFER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Module>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Module> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Module>() {
              public Module findValueByNumber(int number) {
                return Module.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Internal.getDescriptor().getEnumTypes().get(0);
      }

      private static final Module[] VALUES = values();

      public static Module valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Module(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:message.Internal.Module)
    }

    /**
     * Protobuf enum {@code message.Internal.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ACK = 1;</code>
       */
      ACK(1),
      /**
       * <code>ERROR = 2;</code>
       */
      ERROR(2),
      /**
       * <code>GREET = 3;</code>
       */
      GREET(3),
      ;

      /**
       * <code>ACK = 1;</code>
       */
      public static final int ACK_VALUE = 1;
      /**
       * <code>ERROR = 2;</code>
       */
      public static final int ERROR_VALUE = 2;
      /**
       * <code>GREET = 3;</code>
       */
      public static final int GREET_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MsgType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MsgType forNumber(int value) {
        switch (value) {
          case 1: return ACK;
          case 2: return ERROR;
          case 3: return GREET;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Internal.getDescriptor().getEnumTypes().get(1);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:message.Internal.MsgType)
    }

    private int bitField0_;
    public static final int ORIGIN_FIELD_NUMBER = 1;
    private int origin_;
    /**
     * <code>optional .message.Internal.Module origin = 1;</code>
     * @return Whether the origin field is set.
     */
    @Override public boolean hasOrigin() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .message.Internal.Module origin = 1;</code>
     * @return The origin.
     */
    @Override public Module getOrigin() {
      @SuppressWarnings("deprecation")
      Module result = Module.valueOf(origin_);
      return result == null ? Module.CLIENT : result;
    }

    public static final int DEST_FIELD_NUMBER = 2;
    private int dest_;
    /**
     * <code>optional .message.Internal.Module dest = 2;</code>
     * @return Whether the dest field is set.
     */
    @Override public boolean hasDest() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .message.Internal.Module dest = 2;</code>
     * @return The dest.
     */
    @Override public Module getDest() {
      @SuppressWarnings("deprecation")
      Module result = Module.valueOf(dest_);
      return result == null ? Module.CLIENT : result;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 3;
    private int msgType_;
    /**
     * <code>optional .message.Internal.MsgType msgType = 3;</code>
     * @return Whether the msgType field is set.
     */
    @Override public boolean hasMsgType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .message.Internal.MsgType msgType = 3;</code>
     * @return The msgType.
     */
    @Override public MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      MsgType result = MsgType.valueOf(msgType_);
      return result == null ? MsgType.ACK : result;
    }

    public static final int BODY_FIELD_NUMBER = 4;
    private volatile Object body_;
    /**
     * <code>optional string body = 4;</code>
     * @return Whether the body field is set.
     */
    @Override
    public boolean hasBody() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string body = 4;</code>
     * @return The body.
     */
    @Override
    public String getBody() {
      Object ref = body_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string body = 4;</code>
     * @return The bytes for body.
     */
    @Override
    public com.google.protobuf.ByteString
        getBodyBytes() {
      Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTERNALID_FIELD_NUMBER = 5;
    private long internalId_;
    /**
     * <code>optional int64 internalId = 5;</code>
     * @return Whether the internalId field is set.
     */
    @Override
    public boolean hasInternalId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int64 internalId = 5;</code>
     * @return The internalId.
     */
    @Override
    public long getInternalId() {
      return internalId_;
    }

    public static final int CREATETIME_FIELD_NUMBER = 6;
    private long createTime_;
    /**
     * <code>optional int64 createTime = 6;</code>
     * @return Whether the createTime field is set.
     */
    @Override
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int64 createTime = 6;</code>
     * @return The createTime.
     */
    @Override
    public long getCreateTime() {
      return createTime_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, origin_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, dest_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, msgType_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, body_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt64(5, internalId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt64(6, createTime_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, origin_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, dest_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, msgType_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, body_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, internalId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Internal)) {
        return super.equals(obj);
      }
      Internal other = (Internal) obj;

      if (hasOrigin() != other.hasOrigin()) return false;
      if (hasOrigin()) {
        if (origin_ != other.origin_) return false;
      }
      if (hasDest() != other.hasDest()) return false;
      if (hasDest()) {
        if (dest_ != other.dest_) return false;
      }
      if (hasMsgType() != other.hasMsgType()) return false;
      if (hasMsgType()) {
        if (msgType_ != other.msgType_) return false;
      }
      if (hasBody() != other.hasBody()) return false;
      if (hasBody()) {
        if (!getBody()
            .equals(other.getBody())) return false;
      }
      if (hasInternalId() != other.hasInternalId()) return false;
      if (hasInternalId()) {
        if (getInternalId()
            != other.getInternalId()) return false;
      }
      if (hasCreateTime() != other.hasCreateTime()) return false;
      if (hasCreateTime()) {
        if (getCreateTime()
            != other.getCreateTime()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOrigin()) {
        hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
        hash = (53 * hash) + origin_;
      }
      if (hasDest()) {
        hash = (37 * hash) + DEST_FIELD_NUMBER;
        hash = (53 * hash) + dest_;
      }
      if (hasMsgType()) {
        hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + msgType_;
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      if (hasInternalId()) {
        hash = (37 * hash) + INTERNALID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getInternalId());
      }
      if (hasCreateTime()) {
        hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCreateTime());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Internal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Internal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Internal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Internal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Internal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Internal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Internal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Internal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Internal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Internal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Internal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Internal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Internal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.Internal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.Internal)
        InternalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IMInternal.internal_static_message_Internal_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IMInternal.internal_static_message_Internal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Internal.class, Builder.class);
      }

      // Construct using io.drake.im.protobuf.generate.IMInternal.Internal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        origin_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        dest_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        msgType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000004);
        body_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        internalId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IMInternal.internal_static_message_Internal_descriptor;
      }

      @Override
      public Internal getDefaultInstanceForType() {
        return Internal.getDefaultInstance();
      }

      @Override
      public Internal build() {
        Internal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Internal buildPartial() {
        Internal result = new Internal(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.origin_ = origin_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dest_ = dest_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.internalId_ = internalId_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.createTime_ = createTime_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Internal) {
          return mergeFrom((Internal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Internal other) {
        if (other == Internal.getDefaultInstance()) return this;
        if (other.hasOrigin()) {
          setOrigin(other.getOrigin());
        }
        if (other.hasDest()) {
          setDest(other.getDest());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasBody()) {
          bitField0_ |= 0x00000008;
          body_ = other.body_;
          onChanged();
        }
        if (other.hasInternalId()) {
          setInternalId(other.getInternalId());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Internal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Internal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int origin_ = 1;
      /**
       * <code>optional .message.Internal.Module origin = 1;</code>
       * @return Whether the origin field is set.
       */
      @Override public boolean hasOrigin() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .message.Internal.Module origin = 1;</code>
       * @return The origin.
       */
      @Override
      public Module getOrigin() {
        @SuppressWarnings("deprecation")
        Module result = Module.valueOf(origin_);
        return result == null ? Module.CLIENT : result;
      }
      /**
       * <code>optional .message.Internal.Module origin = 1;</code>
       * @param value The origin to set.
       * @return This builder for chaining.
       */
      public Builder setOrigin(Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        origin_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .message.Internal.Module origin = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrigin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        origin_ = 1;
        onChanged();
        return this;
      }

      private int dest_ = 1;
      /**
       * <code>optional .message.Internal.Module dest = 2;</code>
       * @return Whether the dest field is set.
       */
      @Override public boolean hasDest() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .message.Internal.Module dest = 2;</code>
       * @return The dest.
       */
      @Override
      public Module getDest() {
        @SuppressWarnings("deprecation")
        Module result = Module.valueOf(dest_);
        return result == null ? Module.CLIENT : result;
      }
      /**
       * <code>optional .message.Internal.Module dest = 2;</code>
       * @param value The dest to set.
       * @return This builder for chaining.
       */
      public Builder setDest(Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        dest_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .message.Internal.Module dest = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDest() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dest_ = 1;
        onChanged();
        return this;
      }

      private int msgType_ = 1;
      /**
       * <code>optional .message.Internal.MsgType msgType = 3;</code>
       * @return Whether the msgType field is set.
       */
      @Override public boolean hasMsgType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .message.Internal.MsgType msgType = 3;</code>
       * @return The msgType.
       */
      @Override
      public MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        MsgType result = MsgType.valueOf(msgType_);
        return result == null ? MsgType.ACK : result;
      }
      /**
       * <code>optional .message.Internal.MsgType msgType = 3;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .message.Internal.MsgType msgType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgType_ = 1;
        onChanged();
        return this;
      }

      private Object body_ = "";
      /**
       * <code>optional string body = 4;</code>
       * @return Whether the body field is set.
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string body = 4;</code>
       * @return The body.
       */
      public String getBody() {
        Object ref = body_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            body_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string body = 4;</code>
       * @return The bytes for body.
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string body = 4;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string body = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000008);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>optional string body = 4;</code>
       * @param value The bytes for body to set.
       * @return This builder for chaining.
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        body_ = value;
        onChanged();
        return this;
      }

      private long internalId_ ;
      /**
       * <code>optional int64 internalId = 5;</code>
       * @return Whether the internalId field is set.
       */
      @Override
      public boolean hasInternalId() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int64 internalId = 5;</code>
       * @return The internalId.
       */
      @Override
      public long getInternalId() {
        return internalId_;
      }
      /**
       * <code>optional int64 internalId = 5;</code>
       * @param value The internalId to set.
       * @return This builder for chaining.
       */
      public Builder setInternalId(long value) {
        bitField0_ |= 0x00000010;
        internalId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 internalId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearInternalId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        internalId_ = 0L;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>optional int64 createTime = 6;</code>
       * @return Whether the createTime field is set.
       */
      @Override
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int64 createTime = 6;</code>
       * @return The createTime.
       */
      @Override
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>optional int64 createTime = 6;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000020;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 createTime = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        createTime_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.Internal)
    }

    // @@protoc_insertion_point(class_scope:message.Internal)
    private static final Internal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Internal();
    }

    public static Internal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Internal>
        PARSER = new com.google.protobuf.AbstractParser<Internal>() {
      @Override
      public Internal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Internal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Internal> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Internal> getParserForType() {
      return PARSER;
    }

    @Override
    public Internal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Internal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Internal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Internal.proto\022\007message\"\233\002\n\010Internal\022(" +
      "\n\006origin\030\001 \001(\0162\030.message.Internal.Module" +
      "\022&\n\004dest\030\002 \001(\0162\030.message.Internal.Module" +
      "\022*\n\007msgType\030\003 \001(\0162\031.message.Internal.Msg" +
      "Type\022\014\n\004body\030\004 \001(\t\022\022\n\ninternalId\030\005 \001(\003\022\022" +
      "\n\ncreateTime\030\006 \001(\003\"1\n\006Module\022\n\n\006CLIENT\020\001" +
      "\022\r\n\tCONNECTOR\020\002\022\014\n\010TRANSFER\020\003\"(\n\007MsgType" +
      "\022\007\n\003ACK\020\001\022\t\n\005ERROR\020\002\022\t\n\005GREET\020\003B+\n\035io.dr" +
      "ake.im.protobuf.generateB\nIMInternal"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_message_Internal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_Internal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Internal_descriptor,
        new String[] { "Origin", "Dest", "MsgType", "Body", "InternalId", "CreateTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
