// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package io.drake.im.protobuf.generate;

public final class IMMessage {
  private IMMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.ChatMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string originId = 1;</code>
     * @return Whether the originId field is set.
     */
    boolean hasOriginId();
    /**
     * <code>optional string originId = 1;</code>
     * @return The originId.
     */
    String getOriginId();
    /**
     * <code>optional string originId = 1;</code>
     * @return The bytes for originId.
     */
    com.google.protobuf.ByteString
        getOriginIdBytes();

    /**
     * <code>optional string originName = 2;</code>
     * @return Whether the originName field is set.
     */
    boolean hasOriginName();
    /**
     * <code>optional string originName = 2;</code>
     * @return The originName.
     */
    String getOriginName();
    /**
     * <code>optional string originName = 2;</code>
     * @return The bytes for originName.
     */
    com.google.protobuf.ByteString
        getOriginNameBytes();

    /**
     * <code>optional string destId = 3;</code>
     * @return Whether the destId field is set.
     */
    boolean hasDestId();
    /**
     * <code>optional string destId = 3;</code>
     * @return The destId.
     */
    String getDestId();
    /**
     * <code>optional string destId = 3;</code>
     * @return The bytes for destId.
     */
    com.google.protobuf.ByteString
        getDestIdBytes();

    /**
     * <code>repeated string groupMembers = 4;</code>
     * @return A list containing the groupMembers.
     */
    java.util.List<String>
        getGroupMembersList();
    /**
     * <code>repeated string groupMembers = 4;</code>
     * @return The count of groupMembers.
     */
    int getGroupMembersCount();
    /**
     * <code>repeated string groupMembers = 4;</code>
     * @param index The index of the element to return.
     * @return The groupMembers at the given index.
     */
    String getGroupMembers(int index);
    /**
     * <code>repeated string groupMembers = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the groupMembers at the given index.
     */
    com.google.protobuf.ByteString
        getGroupMembersBytes(int index);

    /**
     * <code>optional string content = 5;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <code>optional string content = 5;</code>
     * @return The content.
     */
    String getContent();
    /**
     * <code>optional string content = 5;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>optional int64 createTime = 6;</code>
     * @return Whether the createTime field is set.
     */
    boolean hasCreateTime();
    /**
     * <code>optional int64 createTime = 6;</code>
     * @return The createTime.
     */
    long getCreateTime();

    /**
     * <code>optional bool isSigned = 7 [default = false];</code>
     * @return Whether the isSigned field is set.
     */
    boolean hasIsSigned();
    /**
     * <code>optional bool isSigned = 7 [default = false];</code>
     * @return The isSigned.
     */
    boolean getIsSigned();

    /**
     * <code>optional .message.ChatMsg.MessageType type = 8;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional .message.ChatMsg.MessageType type = 8;</code>
     * @return The type.
     */
    ChatMsg.MessageType getType();
  }
  /**
   * Protobuf type {@code message.ChatMsg}
   */
  public static final class ChatMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.ChatMsg)
      ChatMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatMsg.newBuilder() to construct.
    private ChatMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMsg() {
      originId_ = "";
      originName_ = "";
      destId_ = "";
      groupMembers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      content_ = "";
      type_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatMsg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              originId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              originName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              destId_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                groupMembers_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              groupMembers_.add(bs);
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              content_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              createTime_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              isSigned_ = input.readBool();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              MessageType value = MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                type_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          groupMembers_ = groupMembers_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMMessage.internal_static_message_ChatMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMMessage.internal_static_message_ChatMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatMsg.class, Builder.class);
    }

    /**
     * Protobuf enum {@code message.ChatMsg.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SINGLE = 0;</code>
       */
      SINGLE(0),
      /**
       * <code>GROUP = 1;</code>
       */
      GROUP(1),
      ;

      /**
       * <code>SINGLE = 0;</code>
       */
      public static final int SINGLE_VALUE = 0;
      /**
       * <code>GROUP = 1;</code>
       */
      public static final int GROUP_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return SINGLE;
          case 1: return GROUP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ChatMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:message.ChatMsg.MessageType)
    }

    private int bitField0_;
    public static final int ORIGINID_FIELD_NUMBER = 1;
    private volatile Object originId_;
    /**
     * <code>optional string originId = 1;</code>
     * @return Whether the originId field is set.
     */
    @Override
    public boolean hasOriginId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string originId = 1;</code>
     * @return The originId.
     */
    @Override
    public String getOriginId() {
      Object ref = originId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          originId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string originId = 1;</code>
     * @return The bytes for originId.
     */
    @Override
    public com.google.protobuf.ByteString
        getOriginIdBytes() {
      Object ref = originId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        originId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIGINNAME_FIELD_NUMBER = 2;
    private volatile Object originName_;
    /**
     * <code>optional string originName = 2;</code>
     * @return Whether the originName field is set.
     */
    @Override
    public boolean hasOriginName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string originName = 2;</code>
     * @return The originName.
     */
    @Override
    public String getOriginName() {
      Object ref = originName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          originName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string originName = 2;</code>
     * @return The bytes for originName.
     */
    @Override
    public com.google.protobuf.ByteString
        getOriginNameBytes() {
      Object ref = originName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        originName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTID_FIELD_NUMBER = 3;
    private volatile Object destId_;
    /**
     * <code>optional string destId = 3;</code>
     * @return Whether the destId field is set.
     */
    @Override
    public boolean hasDestId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string destId = 3;</code>
     * @return The destId.
     */
    @Override
    public String getDestId() {
      Object ref = destId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string destId = 3;</code>
     * @return The bytes for destId.
     */
    @Override
    public com.google.protobuf.ByteString
        getDestIdBytes() {
      Object ref = destId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        destId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPMEMBERS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList groupMembers_;
    /**
     * <code>repeated string groupMembers = 4;</code>
     * @return A list containing the groupMembers.
     */
    public com.google.protobuf.ProtocolStringList
        getGroupMembersList() {
      return groupMembers_;
    }
    /**
     * <code>repeated string groupMembers = 4;</code>
     * @return The count of groupMembers.
     */
    public int getGroupMembersCount() {
      return groupMembers_.size();
    }
    /**
     * <code>repeated string groupMembers = 4;</code>
     * @param index The index of the element to return.
     * @return The groupMembers at the given index.
     */
    public String getGroupMembers(int index) {
      return groupMembers_.get(index);
    }
    /**
     * <code>repeated string groupMembers = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the groupMembers at the given index.
     */
    public com.google.protobuf.ByteString
        getGroupMembersBytes(int index) {
      return groupMembers_.getByteString(index);
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private volatile Object content_;
    /**
     * <code>optional string content = 5;</code>
     * @return Whether the content field is set.
     */
    @Override
    public boolean hasContent() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string content = 5;</code>
     * @return The content.
     */
    @Override
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 5;</code>
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 6;
    private long createTime_;
    /**
     * <code>optional int64 createTime = 6;</code>
     * @return Whether the createTime field is set.
     */
    @Override
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int64 createTime = 6;</code>
     * @return The createTime.
     */
    @Override
    public long getCreateTime() {
      return createTime_;
    }

    public static final int ISSIGNED_FIELD_NUMBER = 7;
    private boolean isSigned_;
    /**
     * <code>optional bool isSigned = 7 [default = false];</code>
     * @return Whether the isSigned field is set.
     */
    @Override
    public boolean hasIsSigned() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bool isSigned = 7 [default = false];</code>
     * @return The isSigned.
     */
    @Override
    public boolean getIsSigned() {
      return isSigned_;
    }

    public static final int TYPE_FIELD_NUMBER = 8;
    private int type_;
    /**
     * <code>optional .message.ChatMsg.MessageType type = 8;</code>
     * @return Whether the type field is set.
     */
    @Override public boolean hasType() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional .message.ChatMsg.MessageType type = 8;</code>
     * @return The type.
     */
    @Override public MessageType getType() {
      @SuppressWarnings("deprecation")
      MessageType result = MessageType.valueOf(type_);
      return result == null ? MessageType.SINGLE : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, originId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, originName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, destId_);
      }
      for (int i = 0; i < groupMembers_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, groupMembers_.getRaw(i));
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, content_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt64(6, createTime_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBool(7, isSigned_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeEnum(8, type_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, originId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, originName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, destId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < groupMembers_.size(); i++) {
          dataSize += computeStringSizeNoTag(groupMembers_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getGroupMembersList().size();
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, content_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createTime_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isSigned_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ChatMsg)) {
        return super.equals(obj);
      }
      ChatMsg other = (ChatMsg) obj;

      if (hasOriginId() != other.hasOriginId()) return false;
      if (hasOriginId()) {
        if (!getOriginId()
            .equals(other.getOriginId())) return false;
      }
      if (hasOriginName() != other.hasOriginName()) return false;
      if (hasOriginName()) {
        if (!getOriginName()
            .equals(other.getOriginName())) return false;
      }
      if (hasDestId() != other.hasDestId()) return false;
      if (hasDestId()) {
        if (!getDestId()
            .equals(other.getDestId())) return false;
      }
      if (!getGroupMembersList()
          .equals(other.getGroupMembersList())) return false;
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (hasCreateTime() != other.hasCreateTime()) return false;
      if (hasCreateTime()) {
        if (getCreateTime()
            != other.getCreateTime()) return false;
      }
      if (hasIsSigned() != other.hasIsSigned()) return false;
      if (hasIsSigned()) {
        if (getIsSigned()
            != other.getIsSigned()) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOriginId()) {
        hash = (37 * hash) + ORIGINID_FIELD_NUMBER;
        hash = (53 * hash) + getOriginId().hashCode();
      }
      if (hasOriginName()) {
        hash = (37 * hash) + ORIGINNAME_FIELD_NUMBER;
        hash = (53 * hash) + getOriginName().hashCode();
      }
      if (hasDestId()) {
        hash = (37 * hash) + DESTID_FIELD_NUMBER;
        hash = (53 * hash) + getDestId().hashCode();
      }
      if (getGroupMembersCount() > 0) {
        hash = (37 * hash) + GROUPMEMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getGroupMembersList().hashCode();
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasCreateTime()) {
        hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCreateTime());
      }
      if (hasIsSigned()) {
        hash = (37 * hash) + ISSIGNED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsSigned());
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ChatMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ChatMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.ChatMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.ChatMsg)
        ChatMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IMMessage.internal_static_message_ChatMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IMMessage.internal_static_message_ChatMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ChatMsg.class, Builder.class);
      }

      // Construct using io.drake.im.protobuf.generate.IMMessage.ChatMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        originId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        originName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        destId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        groupMembers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        isSigned_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IMMessage.internal_static_message_ChatMsg_descriptor;
      }

      @Override
      public ChatMsg getDefaultInstanceForType() {
        return ChatMsg.getDefaultInstance();
      }

      @Override
      public ChatMsg build() {
        ChatMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ChatMsg buildPartial() {
        ChatMsg result = new ChatMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.originId_ = originId_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.originName_ = originName_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.destId_ = destId_;
        if (((bitField0_ & 0x00000008) != 0)) {
          groupMembers_ = groupMembers_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.groupMembers_ = groupMembers_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.createTime_ = createTime_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.isSigned_ = isSigned_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ChatMsg) {
          return mergeFrom((ChatMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ChatMsg other) {
        if (other == ChatMsg.getDefaultInstance()) return this;
        if (other.hasOriginId()) {
          bitField0_ |= 0x00000001;
          originId_ = other.originId_;
          onChanged();
        }
        if (other.hasOriginName()) {
          bitField0_ |= 0x00000002;
          originName_ = other.originName_;
          onChanged();
        }
        if (other.hasDestId()) {
          bitField0_ |= 0x00000004;
          destId_ = other.destId_;
          onChanged();
        }
        if (!other.groupMembers_.isEmpty()) {
          if (groupMembers_.isEmpty()) {
            groupMembers_ = other.groupMembers_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureGroupMembersIsMutable();
            groupMembers_.addAll(other.groupMembers_);
          }
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000010;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasIsSigned()) {
          setIsSigned(other.getIsSigned());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ChatMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ChatMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object originId_ = "";
      /**
       * <code>optional string originId = 1;</code>
       * @return Whether the originId field is set.
       */
      public boolean hasOriginId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string originId = 1;</code>
       * @return The originId.
       */
      public String getOriginId() {
        Object ref = originId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            originId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string originId = 1;</code>
       * @return The bytes for originId.
       */
      public com.google.protobuf.ByteString
          getOriginIdBytes() {
        Object ref = originId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          originId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string originId = 1;</code>
       * @param value The originId to set.
       * @return This builder for chaining.
       */
      public Builder setOriginId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        originId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string originId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOriginId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        originId_ = getDefaultInstance().getOriginId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string originId = 1;</code>
       * @param value The bytes for originId to set.
       * @return This builder for chaining.
       */
      public Builder setOriginIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        originId_ = value;
        onChanged();
        return this;
      }

      private Object originName_ = "";
      /**
       * <code>optional string originName = 2;</code>
       * @return Whether the originName field is set.
       */
      public boolean hasOriginName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string originName = 2;</code>
       * @return The originName.
       */
      public String getOriginName() {
        Object ref = originName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            originName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string originName = 2;</code>
       * @return The bytes for originName.
       */
      public com.google.protobuf.ByteString
          getOriginNameBytes() {
        Object ref = originName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          originName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string originName = 2;</code>
       * @param value The originName to set.
       * @return This builder for chaining.
       */
      public Builder setOriginName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        originName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string originName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOriginName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        originName_ = getDefaultInstance().getOriginName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string originName = 2;</code>
       * @param value The bytes for originName to set.
       * @return This builder for chaining.
       */
      public Builder setOriginNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        originName_ = value;
        onChanged();
        return this;
      }

      private Object destId_ = "";
      /**
       * <code>optional string destId = 3;</code>
       * @return Whether the destId field is set.
       */
      public boolean hasDestId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string destId = 3;</code>
       * @return The destId.
       */
      public String getDestId() {
        Object ref = destId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            destId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string destId = 3;</code>
       * @return The bytes for destId.
       */
      public com.google.protobuf.ByteString
          getDestIdBytes() {
        Object ref = destId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          destId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string destId = 3;</code>
       * @param value The destId to set.
       * @return This builder for chaining.
       */
      public Builder setDestId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        destId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string destId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        destId_ = getDefaultInstance().getDestId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string destId = 3;</code>
       * @param value The bytes for destId to set.
       * @return This builder for chaining.
       */
      public Builder setDestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        destId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList groupMembers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureGroupMembersIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          groupMembers_ = new com.google.protobuf.LazyStringArrayList(groupMembers_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string groupMembers = 4;</code>
       * @return A list containing the groupMembers.
       */
      public com.google.protobuf.ProtocolStringList
          getGroupMembersList() {
        return groupMembers_.getUnmodifiableView();
      }
      /**
       * <code>repeated string groupMembers = 4;</code>
       * @return The count of groupMembers.
       */
      public int getGroupMembersCount() {
        return groupMembers_.size();
      }
      /**
       * <code>repeated string groupMembers = 4;</code>
       * @param index The index of the element to return.
       * @return The groupMembers at the given index.
       */
      public String getGroupMembers(int index) {
        return groupMembers_.get(index);
      }
      /**
       * <code>repeated string groupMembers = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the groupMembers at the given index.
       */
      public com.google.protobuf.ByteString
          getGroupMembersBytes(int index) {
        return groupMembers_.getByteString(index);
      }
      /**
       * <code>repeated string groupMembers = 4;</code>
       * @param index The index to set the value at.
       * @param value The groupMembers to set.
       * @return This builder for chaining.
       */
      public Builder setGroupMembers(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGroupMembersIsMutable();
        groupMembers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string groupMembers = 4;</code>
       * @param value The groupMembers to add.
       * @return This builder for chaining.
       */
      public Builder addGroupMembers(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGroupMembersIsMutable();
        groupMembers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string groupMembers = 4;</code>
       * @param values The groupMembers to add.
       * @return This builder for chaining.
       */
      public Builder addAllGroupMembers(
          Iterable<String> values) {
        ensureGroupMembersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, groupMembers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string groupMembers = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupMembers() {
        groupMembers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string groupMembers = 4;</code>
       * @param value The bytes of the groupMembers to add.
       * @return This builder for chaining.
       */
      public Builder addGroupMembersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGroupMembersIsMutable();
        groupMembers_.add(value);
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>optional string content = 5;</code>
       * @return Whether the content field is set.
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string content = 5;</code>
       * @return The content.
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string content = 5;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 5;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000010);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 5;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        content_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>optional int64 createTime = 6;</code>
       * @return Whether the createTime field is set.
       */
      @Override
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int64 createTime = 6;</code>
       * @return The createTime.
       */
      @Override
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>optional int64 createTime = 6;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000020;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 createTime = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private boolean isSigned_ ;
      /**
       * <code>optional bool isSigned = 7 [default = false];</code>
       * @return Whether the isSigned field is set.
       */
      @Override
      public boolean hasIsSigned() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional bool isSigned = 7 [default = false];</code>
       * @return The isSigned.
       */
      @Override
      public boolean getIsSigned() {
        return isSigned_;
      }
      /**
       * <code>optional bool isSigned = 7 [default = false];</code>
       * @param value The isSigned to set.
       * @return This builder for chaining.
       */
      public Builder setIsSigned(boolean value) {
        bitField0_ |= 0x00000040;
        isSigned_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isSigned = 7 [default = false];</code>
       * @return This builder for chaining.
       */
      public Builder clearIsSigned() {
        bitField0_ = (bitField0_ & ~0x00000040);
        isSigned_ = false;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .message.ChatMsg.MessageType type = 8;</code>
       * @return Whether the type field is set.
       */
      @Override public boolean hasType() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional .message.ChatMsg.MessageType type = 8;</code>
       * @return The type.
       */
      @Override
      public MessageType getType() {
        @SuppressWarnings("deprecation")
        MessageType result = MessageType.valueOf(type_);
        return result == null ? MessageType.SINGLE : result;
      }
      /**
       * <code>optional .message.ChatMsg.MessageType type = 8;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .message.ChatMsg.MessageType type = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        type_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.ChatMsg)
    }

    // @@protoc_insertion_point(class_scope:message.ChatMsg)
    private static final ChatMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ChatMsg();
    }

    public static ChatMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<ChatMsg>
        PARSER = new com.google.protobuf.AbstractParser<ChatMsg>() {
      @Override
      public ChatMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ChatMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public ChatMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_ChatMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_ChatMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tMsg.proto\022\007message\"\345\001\n\007ChatMsg\022\020\n\010orig" +
      "inId\030\001 \001(\t\022\022\n\noriginName\030\002 \001(\t\022\016\n\006destId" +
      "\030\003 \001(\t\022\024\n\014groupMembers\030\004 \003(\t\022\017\n\007content\030" +
      "\005 \001(\t\022\022\n\ncreateTime\030\006 \001(\003\022\027\n\010isSigned\030\007 " +
      "\001(\010:\005false\022*\n\004type\030\010 \001(\0162\034.message.ChatM" +
      "sg.MessageType\"$\n\013MessageType\022\n\n\006SINGLE\020" +
      "\000\022\t\n\005GROUP\020\001B*\n\035io.drake.im.protobuf.gen" +
      "erateB\tIMMessage"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_message_ChatMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_ChatMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_ChatMsg_descriptor,
        new String[] { "OriginId", "OriginName", "DestId", "GroupMembers", "Content", "CreateTime", "IsSigned", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
